export { IndustryHero, type IndustryHeroProps } from './IndustryHero';
export { IndustryWhoWeServe, type IndustryWhoWeServeProps } from './IndustryWhoWeServe';
export { IndustryPressures, type IndustryPressuresProps, type PressureItem } from './IndustryPressures';
export { IndustryCapabilities, type IndustryCapabilitiesProps, type CapabilityGroup } from './IndustryCapabilities';
export { IndustrySolutions, type IndustrySolutionsProps, type SolutionGroup } from './IndustrySolutions';
export { IndustryCompliance, type IndustryComplianceProps, type ComplianceSafeguard } from './IndustryCompliance';
export { IndustrySegments, type IndustrySegmentsProps, type Segment } from './IndustrySegments';
export { IndustryTechStandards, type IndustryTechStandardsProps } from './IndustryTechStandards';
export { IndustryServices, type IndustryServicesProps, type ServiceLink } from './IndustryServices';
export { IndustryFaq, type IndustryFaqProps } from './IndustryFaq';
export { IndustryCta, type IndustryCtaProps } from './IndustryCta';
