export { HeroSection } from './HeroSection';
export { ExperienceSection } from './ExperienceSection';
export { PartnersSection } from './PartnersSection';
export { ServicesSection } from './ServicesSection';
export { WhyChooseUsSection } from './WhyChooseUsSection';
export { CaseStudiesSection } from './CaseStudiesSection';
export { TestimonialsSection } from './TestimonialsSection';
export { FAQSection } from './FAQSection';
export { CTASection } from './CTASection';
